language: cpp

addons:
  apt:
    packages:
      - g++-5
      - libboost-dev
      - doxygen
      - libgtest-dev
      - valgrind
    sources:
      - ubuntu-toolchain-r-test

install:
   - mkdir gtest
   - cd gtest
   - export LIBRARY_PATH=$(pwd)
   - cp -r /usr/src/gtest/* ./
   - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
   - make
   - cd -

script:
    - make test
