language: cpp

compiler:
    - gcc

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - g++-5
      - libboost-dev
      - libgtest-dev
      - valgrind

install:
    - mkdir gtest
    - cd gtest
    - echo $(pwd)
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - ls -al
    - cd -

before_script:
    - uname -a
    - printenv
    - doxygen --version
    - g++-5 --version
    - gcov-5 --version
    - gprof --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - dpkg -l libgtest-dev
    - valgrind --version

install:
   - mkdir gtest
   - cd gtest
   - export LIBRARY_PATH=$(pwd)
   - cp -r /usr/src/gtest/* ./
   - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
   - make
   - cd -

script:
    - date
    - ls -al
    - make test
